load("@rules_android//rules:rules.bzl", "android_library")

package(default_visibility = ["//visibility:public"])

DEPS = [
    "//modules/core",
    "//modules/musictheory",
    "//modules/platform",
    "//modules/thread",
]

cc_library(
    name = "midi",
    srcs = glob(["src/*.c"]) + select({
        "//bazel/config:plat_macos": glob(["macos/src/*.c", "macos/src/*.h"], allow_empty = True),
        "//bazel/config:plat_ios": glob(["macos/src/*.c", "macos/src/*.h"], allow_empty = True),
        "//bazel/config:plat_linux": glob(["linux/src/*.c", "linux/src/*.h"], allow_empty = True),
        "//bazel/config:plat_win32": glob(["win32/src/*.c", "win32/src/*.h"], allow_empty = True),
        "//bazel/config:plat_android": glob(["android/src/*.c", "android/src/*.h"], allow_empty = True),
        "//conditions:default": [],
    }),
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    linkopts = select({
        "//bazel/config:plat_macos": ["-framework", "CoreMIDI", "-framework", "CoreFoundation"],
        "//bazel/config:plat_ios": ["-framework", "CoreMIDI", "-framework", "CoreFoundation"],
        "//bazel/config:plat_win32": ["-lwinmm"],
        "//conditions:default": [],
    }),
    deps = DEPS + select({
        "//bazel/config:plat_macos": [":midi_macos"],
        "//conditions:default": [],
    }),
)

android_library(
    name = "android_java",
    srcs = glob(["android/java/**/*.java"]),
    custom_package = "orgwall.melody.midi",
    exports_manifest = True,
    manifest = "android/AndroidManifest.xml",
    target_compatible_with = select({
        "//bazel/config:plat_android": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

objc_library(
    name = "midi_macos",
    srcs = glob(["macos/src/*.m", "include/**/*.h"], allow_empty = True),
    includes = ["include"],
    deps = DEPS,
    target_compatible_with = select({
        "//bazel/config:plat_macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
