#version 460
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 1) in;

layout(set = 2, binding = 0, std430) readonly buffer Survivors { uint count; } surv_buf[];
layout(set = 2, binding = 0, std430) buffer Indirect { uint gx; uint gy; uint gz; } args_buf[];

layout(push_constant, std430) uniform Root
{
    uint survivors;
    uint args;
    uint local;
    uint pad;
} root;

void main()
{
    uint n = surv_buf[nonuniformEXT(root.survivors)].count;
    uint gx = (n + root.local - 1u) / root.local;
    args_buf[nonuniformEXT(root.args)].gx = gx;
    args_buf[nonuniformEXT(root.args)].gy = 1u;
    args_buf[nonuniformEXT(root.args)].gz = 1u;
}
