package(default_visibility = ["//visibility:public"])

cc_library(
    name = "server",
    srcs = glob(["src/*.c"]),
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    deps = [
        "//modules/core",
        "//modules/allocator",
        "//modules/collection",
        "//modules/log",
        "//modules/string",
        "//third-party/mongoose",
    ],
)
