#pragma once

#ifndef MEL_SERVER_TLS
#define MEL_SERVER_TLS 0
#endif

#ifndef MEL_SERVER_REGISTRY_INITIAL_CAPACITY
#define MEL_SERVER_REGISTRY_INITIAL_CAPACITY 4
#endif

#ifndef MEL_SERVER_DEFAULT_PUBLISH_QUEUE_CAPACITY
#define MEL_SERVER_DEFAULT_PUBLISH_QUEUE_CAPACITY 1024
#endif

#ifndef MEL_SERVER_DEFAULT_PUBLISH_PAYLOAD_LIMIT
#define MEL_SERVER_DEFAULT_PUBLISH_PAYLOAD_LIMIT (64 * 1024)
#endif

#ifndef MEL_SERVER_DEFAULT_CONN_OUTBOX_CAPACITY
#define MEL_SERVER_DEFAULT_CONN_OUTBOX_CAPACITY 256
#endif

#ifndef MEL_SERVER_DEFAULT_ROUTE_CAPTURES
#define MEL_SERVER_DEFAULT_ROUTE_CAPTURES 8
#endif

#ifndef MEL_SERVER_LOG_DOMAIN
#define MEL_SERVER_LOG_DOMAIN "server"
#endif

#ifndef MEL_SERVER_LOG_DOMAIN_ROUTER
#define MEL_SERVER_LOG_DOMAIN_ROUTER "server.router"
#endif

#ifndef MEL_SERVER_LOG_DOMAIN_RPC
#define MEL_SERVER_LOG_DOMAIN_RPC "server.rpc"
#endif

#ifndef MEL_SERVER_LOG_DOMAIN_PUBSUB
#define MEL_SERVER_LOG_DOMAIN_PUBSUB "server.pubsub"
#endif

#ifndef MEL_SERVER_LOG_DOMAIN_WS
#define MEL_SERVER_LOG_DOMAIN_WS "server.ws"
#endif
