package(default_visibility = ["//visibility:public"])

DEPS = [
    "//modules/core",
    "//modules/allocator",
    "//modules/collection",
    "//modules/string",
    "//modules/executor",
    "//modules/future",
    "//modules/event",
    "//modules/vat",
    "//modules/log",
    "//modules/platform",
]

cc_library(
    name = "clipboard",
    srcs = glob(["src/*.c"]) + select({
        "//bazel/config:plat_win32": glob(["win32/src/*.c", "win32/src/*.h"], allow_empty = True),
        "//bazel/config:plat_android": glob(["android/src/*.c", "android/src/*.h"], allow_empty = True),
        "//bazel/config:plat_wasm": glob(["web/src/*.c", "web/src/*.h"], allow_empty = True),
        "//bazel/config:plat_linux": glob(["linux/src/*.c", "linux/src/*.h"]),
        "//conditions:default": [],
    }),
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    linkopts = select({
        "//bazel/config:plat_linux": ["-ldl"],
        "//bazel/config:plat_macos": ["-framework", "AppKit", "-framework", "Foundation"],
        "//bazel/config:plat_ios": ["-framework", "UIKit", "-framework", "Foundation"],
        "//conditions:default": [],
    }),
    deps = DEPS + select({
        "//bazel/config:plat_macos": [":clipboard_apple"],
        "//bazel/config:plat_ios": [":clipboard_apple"],
        "//conditions:default": [],
    }),
)

objc_library(
    name = "clipboard_apple",
    srcs = glob(["apple/src/*.m", "include/**/*.h"]),
    includes = ["include"],
    deps = DEPS,
    target_compatible_with = select({
        "//bazel/config:plat_macos": [],
        "//bazel/config:plat_ios": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

cc_test(
    name = "clipboard-core",
    srcs = ["src/clipboard.c", "test/test.clipboard.c"] + glob(["include/**/*.h"]),
    includes = ["include"],
    linkopts = select({
        "//bazel/config:plat_macos": ["-framework", "AppKit"],
        "//conditions:default": [],
    }),
    deps = [
        "//tools/test:runner",
        "//modules/test",
        "//modules/core",
        "//modules/string",
        "//modules/allocator",
        "//modules/collection",
        "//modules/executor",
        "//modules/future",
        "//modules/event",
        "//modules/vat",
        "//modules/log",
    ],
)
