package(default_visibility = ["//visibility:public"])

cc_library(
    name = "log",
    srcs = glob(["src/*.c"]),
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    linkopts = select({
        "//bazel/config:plat_android": ["-llog"],
        "//conditions:default": [],
    }),
    deps = [
        "//modules/core",
        "//modules/allocator",
        "//modules/collection",
        "//modules/string",
        "//modules/thread",
        "//modules/time",
        "//third-party/sqlite3",
    ],
)
