package(default_visibility = ["//visibility:public"])

DEPS = [
    "//modules/core",
    "//modules/math",
    "//modules/frequency",
    "//modules/musictuning",
    "//modules/allocator",
    "//modules/collection",
    "//third-party/cppcoro",
]

cc_library(
    name = "musictheory",
    srcs = glob(["src/*.c", "src/*.cc"]),
    hdrs = glob(["include/**/*.h"]),
    includes = ["include", "include/musictheory"],
    deps = DEPS,
)

cc_test(
    name = "musictheory-test",
    srcs = ["test/test_musictheory.c"],
    deps = [
        "//tools/test:runner",
        "//modules/test",
        ":musictheory",
    ],
)
