#pragma once

#define MEL_MEMORY_DEBUG_NONE     0
#define MEL_MEMORY_DEBUG_LIGHT    1
#define MEL_MEMORY_DEBUG_HEAVY    2
#define MEL_MEMORY_DEBUG_PARANOID 3

#ifndef MEL_MEMORY_DEBUG
#define MEL_MEMORY_DEBUG MEL_MEMORY_DEBUG_NONE
#endif

#define MEL_GUARD_FLAG_CANARY_HEAD   (1u << 0)
#define MEL_GUARD_FLAG_CANARY_TAIL   (1u << 1)
#define MEL_GUARD_FLAG_POISON_ALLOC  (1u << 2)
#define MEL_GUARD_FLAG_POISON_FREE   (1u << 3)
#define MEL_GUARD_FLAG_QUARANTINE    (1u << 4)
#define MEL_GUARD_FLAG_PAGE_PROTECT  (1u << 5)
#define MEL_GUARD_FLAG_CHECK_ALLOC   (1u << 6)
#define MEL_GUARD_FLAG_CHECK_FREE    (1u << 7)
