#pragma once

#ifndef MEL_IO_DEFAULT_SQ_CAPACITY
# define MEL_IO_DEFAULT_SQ_CAPACITY 256
#endif

#ifndef MEL_IO_DEFAULT_CQ_CAPACITY
# define MEL_IO_DEFAULT_CQ_CAPACITY 512
#endif

#ifndef MEL_IO_MAX_HANDLERS
# define MEL_IO_MAX_HANDLERS 64
#endif

#define MEL_IO_QOS_LATENCY_CRITICAL 0
#define MEL_IO_QOS_STREAMING        1
#define MEL_IO_QOS_BULK             2
#define MEL_IO_QOS_LANE_COUNT       3
