load("@rules_android//rules:rules.bzl", "android_binary")
load("@rules_apple//apple:macos.bzl", "macos_application")
load("@rules_apple//apple:versioning.bzl", "apple_bundle_version")

package(default_visibility = ["//visibility:public"])

DEPS = [
    "//modules/boot",
    "//modules/vat",
    "//modules/allocator",
    "//modules/gui",
    "//modules/display",
    "//modules/core",
    "//modules/color",
    "//modules/paint",
]

cc_library(
    name = "lib",
    srcs = glob(["src/*.c", "src/*.h"]),
    linkopts = select({
        "//bazel/config:plat_macos": ["-framework", "Metal"],
        "//conditions:default": [],
    }),
    deps = DEPS + select({
        "//bazel/config:plat_macos": [":display-gui_macos"],
        "//conditions:default": [],
    }),
)

cc_binary(
    name = "display-gui",
    deps = [":lib"],
)

objc_library(
    name = "display-gui_macos",
    srcs = glob(["macos/src/*.m", "macos/src/*.h", "src/*.h"], allow_empty = True),
    deps = DEPS,
    linkopts = ["-framework", "Cocoa", "-framework", "Metal", "-framework", "QuartzCore"],
    target_compatible_with = select({
        "//bazel/config:plat_macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

apple_bundle_version(
    name = "version",
    build_version = "1.0.0",
)

macos_application(
    name = "display-gui_app",
    bundle_id = "orgwall.displaygui",
    bundle_name = "display-gui",
    infoplists = ["macos/Info.plist"],
    minimum_os_version = "14.4",
    target_compatible_with = ["@platforms//os:macos"],
    version = ":version",
    deps = [":lib"],
)

android_binary(
    name = "melody",
    custom_package = "orgwall.displaygui",
    manifest = "android/AndroidManifest.xml",
    manifest_values = {"appLabel": "Display GUI"},
    target_compatible_with = ["@platforms//os:android"],
    deps = [
        ":lib",
        "//modules/gui:android_java",
        "//modules/display:android_java",
    ],
)
