package(default_visibility = ["//visibility:public"])

cc_library(
    name = "reflect",
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    deps = ["//modules/string"],
)

cc_binary(
    name = "enum-str-gen",
    srcs = ["codegen/enum_str_gen.c"],
    deps = ["@llvm//:libclang"],
)
