package(default_visibility = ["//visibility:public"])

DEPS = ["//modules/core", "//modules/math", "//modules/frequency", "//modules/musictuning", "//modules/musictheory", "//modules/allocator", "//modules/collection", "//modules/string", "//third-party/cppcoro"]

cc_library(
    name = "musicnotation",
    srcs = glob(["src/*.c", "src/*.cc"]),
    hdrs = glob(["include/**/*.h"]),
    includes = ["include", "include/musicnotation"],
    deps = DEPS,
)

cc_test(
    name = "notation-test",
    srcs = ["test/test_notation.c"],
    deps = ["//tools/test:runner", "//modules/test", ":musicnotation", "//modules/core", "//modules/allocator"],
)
