package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pitchdetect",
    srcs = glob(["src/*.c"]),
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    deps = [
        "//modules/core",
        "//modules/allocator",
    ],
)

cc_test(
    name = "pitchdetect-test",
    srcs = ["test/test_pitchdetect.c"],
    deps = [
        "//tools/test:runner",
        "//modules/test",
        ":pitchdetect",
    ],
)
