load("@rules_android//rules:rules.bzl", "android_binary")
load("@rules_apple//apple:ios.bzl", "ios_application")
load("@rules_apple//apple:macos.bzl", "macos_application")
load("@rules_apple//apple:versioning.bzl", "apple_bundle_version")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lib",
    srcs = glob(["src/*.c", "src/*.h"]),
    deps = [
        "//modules/boot",
        "//modules/vat",
        "//modules/allocator",
        "//modules/core",
        "//modules/gui",
        "//modules/gpu",
        "//modules/log",
        "//modules/string",
    ],
)

cc_binary(
    name = "ballgame",
    deps = [":lib"],
)

apple_bundle_version(
    name = "version",
    build_version = "1.0.0",
)

macos_application(
    name = "ballgame_app",
    bundle_id = "orgwall.ballgame",
    bundle_name = "ballgame",
    infoplists = ["macos/Info.plist"],
    minimum_os_version = "14.4",
    target_compatible_with = ["@platforms//os:macos"],
    version = ":version",
    deps = [":lib"],
)

ios_application(
    name = "ballgame_ios",
    bundle_id = "orgwall.ballgame",
    bundle_name = "ballgame",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["ios/Info.plist"],
    minimum_os_version = "14.4",
    target_compatible_with = ["@platforms//os:ios"],
    version = ":version",
    deps = [
        ":lib",
        "//third-party/slang:slang_ios_framework",
    ],
)

android_binary(
    name = "melody",
    custom_package = "orgwall.ballgame",
    manifest = "android/AndroidManifest.xml",
    manifest_values = {"appLabel": "Ball Game"},
    target_compatible_with = ["@platforms//os:android"],
    deps = [
        ":lib",
        "//modules/gui:android_java",
    ],
)
