load("@rules_apple//apple:ios.bzl", "ios_application")
load("@rules_apple//apple:macos.bzl", "macos_application")
load("@rules_apple//apple:versioning.bzl", "apple_bundle_version")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lib",
    srcs = glob(["src/*.c"]),
    deps = [
        "//modules/camera",
        "//modules/barcode",
        "//modules/image",
        "//modules/boot",
        "//modules/vat",
        "//modules/future",
        "//modules/executor",
        "//modules/allocator",
        "//modules/string",
        "//modules/log",
        "//modules/core",
    ],
)

cc_binary(
    name = "barcode-reader",
    deps = [":lib"],
)

apple_bundle_version(
    name = "version",
    build_version = "1.0.0",
)

macos_application(
    name = "barcode-reader_app",
    bundle_id = "orgwall.barcodereader",
    bundle_name = "barcode-reader",
    infoplists = ["macos/Info.plist"],
    minimum_os_version = "14.4",
    target_compatible_with = ["@platforms//os:macos"],
    version = ":version",
    deps = [":lib"],
)

ios_application(
    name = "barcode-reader_ios",
    bundle_id = "orgwall.barcodereader",
    bundle_name = "barcode-reader",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["ios/Info.plist"],
    minimum_os_version = "14.4",
    target_compatible_with = ["@platforms//os:ios"],
    version = ":version",
    deps = [":lib"],
)
