load("@rules_apple//apple:macos.bzl", "macos_application")
load("@rules_apple//apple:versioning.bzl", "apple_bundle_version")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lib",
    srcs = glob(["src/*.c"]),
    deps = [
        "//modules/window",
        "//modules/boot",
        "//modules/vat",
        "//modules/allocator",
        "//modules/string",
        "//modules/core",
    ],
)

cc_binary(
    name = "hello-window",
    deps = [":lib"],
)

apple_bundle_version(
    name = "version",
    build_version = "1.0.0",
)

macos_application(
    name = "hello-window_app",
    bundle_id = "orgwall.hellowindow",
    bundle_name = "hello-window",
    infoplists = ["macos/Info.plist"],
    minimum_os_version = "14.4",
    target_compatible_with = ["@platforms//os:macos"],
    version = ":version",
    deps = [":lib"],
)
