package(default_visibility = ["//visibility:public"])

cc_library(
    name = "layout",
    srcs = glob(["src/*.c"]),
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    deps = [
        "//modules/core",
        "//modules/string",
    ],
)

cc_test(
    name = "layout-test",
    srcs = ["test/layout_test.c"],
    deps = [
        "//tools/test:runner",
        "//modules/test",
        ":layout",
    ],
)
