load("@rules_android//rules:rules.bzl", "android_binary")
load("@rules_apple//apple:ios.bzl", "ios_application")
load("@rules_apple//apple:macos.bzl", "macos_application")
load("@rules_apple//apple:versioning.bzl", "apple_bundle_version")
load("//bazel/rules:mel_wasm.bzl", "mel_wasm_app")
load("//bazel/rules:mel_win32_resources.bzl", "mel_win32_resources")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lib",
    srcs = glob(["src/*.c", "src/*.h"]),
    deps = [
        "//modules/boot",
        "//modules/vat",
        "//modules/allocator",
        "//modules/gui",
        "//modules/core",
        "//modules/color",
        "//modules/paint",
    ],
)

mel_win32_resources(
    name = "win32_resources",
    app_label = "Hello World GUI",
    icon = "win32/app.ico",
    target_compatible_with = ["@platforms//os:windows"],
)

cc_binary(
    name = "hello-world-gui",
    linkopts = select({
        "//bazel/config:plat_win32": ["-Wl,/subsystem:windows"],
        "//conditions:default": [],
    }),
    deps = [":lib"] + select({
        "//bazel/config:plat_win32": [":win32_resources"],
        "//conditions:default": [],
    }),
)

apple_bundle_version(
    name = "version",
    build_version = "1.0.0",
)

macos_application(
    name = "hello-world-gui_app",
    bundle_id = "orgwall.helloworld",
    bundle_name = "hello-world-gui",
    infoplists = ["macos/Info.plist"],
    minimum_os_version = "14.4",
    target_compatible_with = ["@platforms//os:macos"],
    version = ":version",
    deps = [":lib"],
)

ios_application(
    name = "hello-world-gui_ios",
    bundle_id = "orgwall.helloworld",
    bundle_name = "hello-world-gui",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["ios/Info.plist"],
    minimum_os_version = "14.4",
    target_compatible_with = ["@platforms//os:ios"],
    version = ":version",
    deps = [":lib"],
)

android_binary(
    name = "melody",
    custom_package = "orgwall.helloworld",
    manifest = "android/AndroidManifest.xml",
    manifest_values = {"appLabel": "Hello World GUI"},
    target_compatible_with = ["@platforms//os:android"],
    deps = [
        ":lib",
        "//modules/gui:android_java",
    ],
)

mel_wasm_app(
    name = "hello-world-gui_web",
    deps = [":lib"],
)
