load("@rules_android//rules:rules.bzl", "android_library")

package(default_visibility = ["//visibility:public"])

DEPS = [
    "//modules/core",
    "//modules/allocator",
    "//modules/collection",
    "//modules/event",
    "//modules/executor",
    "//modules/future",
    "//modules/port",
    "//modules/vat",
    "//modules/log",
    "//modules/platform",
]

cc_library(
    name = "hid",
    srcs = glob(["src/*.c", "src/*.h"]) + select({
        "//bazel/config:plat_linux": glob(["linux/src/*.c", "linux/src/*.h"], allow_empty = True),
        "//bazel/config:plat_win32": glob(["win32/src/*.c", "win32/src/*.h"], allow_empty = True),
        "//bazel/config:plat_android": glob(["android/src/*.c", "android/src/*.h"], allow_empty = True),
        "//bazel/config:plat_wasm": glob(["wasm/src/*.c"]),
        "//conditions:default": [],
    }),
    hdrs = glob([
        "include/**/*.h",
        "macos/include/**/*.h",
        "ios/include/**/*.h",
        "linux/include/**/*.h",
        "win32/include/**/*.h",
        "android/include/**/*.h",
        "wasm/include/**/*.h",
    ]),
    includes = [
        "include",
        "macos/include",
        "ios/include",
        "linux/include",
        "win32/include",
        "android/include",
        "wasm/include",
    ],
    linkopts = select({
        "//bazel/config:plat_macos": ["-framework", "IOKit", "-framework", "CoreFoundation"],
        "//bazel/config:plat_linux": ["-ludev"],
        "//bazel/config:plat_win32": ["hid.lib", "setupapi.lib"],
        "//conditions:default": [],
    }),
    deps = DEPS + select({
        "//bazel/config:plat_macos": [":hid_apple"],
        "//bazel/config:plat_ios": [":hid_apple"],
        "//conditions:default": [],
    }),
)

android_library(
    name = "android_java",
    srcs = glob(["android/java/**/*.java"]),
    custom_package = "orgwall.melody.hid",
    target_compatible_with = select({
        "//bazel/config:plat_android": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

objc_library(
    name = "hid_apple",
    srcs = glob([
        "src/*.h",
        "include/**/*.h",
        "macos/include/**/*.h",
        "ios/include/**/*.h",
    ]) + select({
        "//bazel/config:plat_macos": glob(["macos/src/*.m"]),
        "//bazel/config:plat_ios": glob(["ios/src/*.m"]),
        "//conditions:default": [],
    }),
    includes = [
        "include",
        "macos/include",
        "ios/include",
    ],
    deps = DEPS,
    target_compatible_with = select({
        "//bazel/config:plat_macos": [],
        "//bazel/config:plat_ios": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

cc_test(
    name = "hid-core",
    srcs = ["test/hid_test.c", "src/hid_internal.h"],
    deps = [
        "//tools/test:runner",
        "//modules/test",
        ":hid",
    ],
)
