#pragma once

#include <core/types.h>

typedef enum {
    MEL_KEY_NONE = 0,

    MEL_KEY_BACKSPACE = 8,
    MEL_KEY_TAB       = 9,
    MEL_KEY_ENTER     = 13,
    MEL_KEY_ESCAPE    = 27,
    MEL_KEY_SPACE     = 32,

    MEL_KEY_0 = '0',
    MEL_KEY_1, MEL_KEY_2, MEL_KEY_3, MEL_KEY_4,
    MEL_KEY_5, MEL_KEY_6, MEL_KEY_7, MEL_KEY_8, MEL_KEY_9,

    MEL_KEY_A = 'A',
    MEL_KEY_B, MEL_KEY_C, MEL_KEY_D, MEL_KEY_E, MEL_KEY_F, MEL_KEY_G,
    MEL_KEY_H, MEL_KEY_I, MEL_KEY_J, MEL_KEY_K, MEL_KEY_L, MEL_KEY_M,
    MEL_KEY_N, MEL_KEY_O, MEL_KEY_P, MEL_KEY_Q, MEL_KEY_R, MEL_KEY_S,
    MEL_KEY_T, MEL_KEY_U, MEL_KEY_V, MEL_KEY_W, MEL_KEY_X, MEL_KEY_Y,
    MEL_KEY_Z,

    MEL_KEY_LEFT = 0x1000,
    MEL_KEY_RIGHT, MEL_KEY_UP, MEL_KEY_DOWN,
    MEL_KEY_HOME, MEL_KEY_END, MEL_KEY_PAGE_UP, MEL_KEY_PAGE_DOWN,
    MEL_KEY_INSERT, MEL_KEY_DELETE,
    MEL_KEY_F1, MEL_KEY_F2, MEL_KEY_F3, MEL_KEY_F4, MEL_KEY_F5, MEL_KEY_F6,
    MEL_KEY_F7, MEL_KEY_F8, MEL_KEY_F9, MEL_KEY_F10, MEL_KEY_F11, MEL_KEY_F12,
    MEL_KEY_SHIFT, MEL_KEY_CONTROL, MEL_KEY_ALT,
} Mel_Key;

typedef enum {
    MEL_MOUSE_LEFT = 0,
    MEL_MOUSE_RIGHT,
    MEL_MOUSE_MIDDLE,
} Mel_Mouse_Button;
