#pragma once

#include <core/types.h>
#include <core/platform.h>

#if MEL_PLATFORM_WINDOWS

#define MEL_THREAD_HANDLE_SIZE     8
#define MEL_THREAD_HANDLE_ALIGN    8

#define MEL_MUTEX_STORAGE_SIZE    16
#define MEL_MUTEX_STORAGE_ALIGN    8

#define MEL_COND_STORAGE_SIZE      8
#define MEL_COND_STORAGE_ALIGN     8

#define MEL_RWLOCK_STORAGE_SIZE    8
#define MEL_RWLOCK_STORAGE_ALIGN   8

#define MEL_SEM_STORAGE_SIZE       8
#define MEL_SEM_STORAGE_ALIGN      8

#define MEL_ONCE_STORAGE_SIZE      8
#define MEL_ONCE_STORAGE_ALIGN     8

#define MEL_TLS_STORAGE_SIZE       4
#define MEL_TLS_STORAGE_ALIGN      4

#define MEL_EVENT_STORAGE_SIZE     8
#define MEL_EVENT_STORAGE_ALIGN    8

#define MEL_BARRIER_STORAGE_SIZE  32
#define MEL_BARRIER_STORAGE_ALIGN  8

#elif MEL_PLATFORM_APPLE

#define MEL_THREAD_HANDLE_SIZE     8
#define MEL_THREAD_HANDLE_ALIGN    8

#define MEL_MUTEX_STORAGE_SIZE    64
#define MEL_MUTEX_STORAGE_ALIGN    8

#define MEL_COND_STORAGE_SIZE     48
#define MEL_COND_STORAGE_ALIGN     8

#define MEL_RWLOCK_STORAGE_SIZE  200
#define MEL_RWLOCK_STORAGE_ALIGN   8

#define MEL_SEM_STORAGE_SIZE       8
#define MEL_SEM_STORAGE_ALIGN      8

#define MEL_ONCE_STORAGE_SIZE      8
#define MEL_ONCE_STORAGE_ALIGN     8

#define MEL_TLS_STORAGE_SIZE       8
#define MEL_TLS_STORAGE_ALIGN      8

#define MEL_EVENT_STORAGE_SIZE    16
#define MEL_EVENT_STORAGE_ALIGN    8

#define MEL_BARRIER_STORAGE_SIZE  32
#define MEL_BARRIER_STORAGE_ALIGN  8

#else

#define MEL_THREAD_HANDLE_SIZE     8
#define MEL_THREAD_HANDLE_ALIGN    8

#define MEL_MUTEX_STORAGE_SIZE    64
#define MEL_MUTEX_STORAGE_ALIGN    8

#define MEL_COND_STORAGE_SIZE     64
#define MEL_COND_STORAGE_ALIGN     8

#define MEL_RWLOCK_STORAGE_SIZE   64
#define MEL_RWLOCK_STORAGE_ALIGN   8

#define MEL_SEM_STORAGE_SIZE      32
#define MEL_SEM_STORAGE_ALIGN      8

#define MEL_ONCE_STORAGE_SIZE      8
#define MEL_ONCE_STORAGE_ALIGN     4

#define MEL_TLS_STORAGE_SIZE       8
#define MEL_TLS_STORAGE_ALIGN      8

#define MEL_EVENT_STORAGE_SIZE    16
#define MEL_EVENT_STORAGE_ALIGN    8

#define MEL_BARRIER_STORAGE_SIZE  64
#define MEL_BARRIER_STORAGE_ALIGN  8

#endif
