package(default_visibility = ["//visibility:public"])

cc_library(
    name = "job",
    srcs = glob(["src/*.c"]),
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    deps = [
        "//modules/core",
        "//modules/allocator",
        "//modules/collection",
        "//modules/thread",
        "//modules/fiber",
        "//modules/signal",
        "//modules/executor",
    ],
)

cc_test(
    name = "job-executor",
    srcs = ["test/test_job.c"],
    deps = [
        "//tools/test:runner",
        "//modules/test",
        ":job",
    ],
)
