#pragma once

#include <core/types.h>

// D3D12-style resource-state model (gpu-rhi.md §7.3 / U17). The full set is carried so that later
// units (sparse, video, ML, accel-struct) do not change every transition site (MEL-ENGINE-VII). The
// Vulkan backend implements the load-bearing subset; an unimplemented state maps conservatively to
// GENERAL with an all-stages/all-access barrier and is flagged at the call site in debug.
typedef enum
{
    MEL_GPU_STATE_COMMON = 0,
    MEL_GPU_STATE_VERTEX_BUFFER,
    MEL_GPU_STATE_INDEX_BUFFER,
    MEL_GPU_STATE_CONSTANT_BUFFER,
    MEL_GPU_STATE_SHADER_RESOURCE,
    MEL_GPU_STATE_UNORDERED_ACCESS,
    MEL_GPU_STATE_RENDER_TARGET,
    MEL_GPU_STATE_DEPTH_WRITE,
    MEL_GPU_STATE_DEPTH_READ,
    MEL_GPU_STATE_COPY_SOURCE,
    MEL_GPU_STATE_COPY_DEST,
    MEL_GPU_STATE_RESOLVE_SOURCE,
    MEL_GPU_STATE_RESOLVE_DEST,
    MEL_GPU_STATE_INDIRECT_ARGUMENT,
    MEL_GPU_STATE_PREDICATION,
    MEL_GPU_STATE_STREAM_OUTPUT,
    MEL_GPU_STATE_PRESENT,
    MEL_GPU_STATE_RAY_TRACING_ACCEL_STRUCT,
    MEL_GPU_STATE_ACCEL_STRUCT_BUILD_READ,
    MEL_GPU_STATE_ACCEL_STRUCT_BUILD_WRITE,
    MEL_GPU_STATE_SHADING_RATE_SOURCE,
    MEL_GPU_STATE_VIDEO_DECODE_READ,
    MEL_GPU_STATE_VIDEO_DECODE_WRITE,
    MEL_GPU_STATE_VIDEO_ENCODE_READ,
    MEL_GPU_STATE_VIDEO_ENCODE_WRITE,
    MEL_GPU_STATE_VIDEO_PROCESS_READ,
    MEL_GPU_STATE_VIDEO_PROCESS_WRITE,
    MEL_GPU_STATE_ML_TENSOR_READ,
    MEL_GPU_STATE_ML_TENSOR_WRITE,
    MEL_GPU_STATE_SPARSE_BINDING_READ,
    MEL_GPU_STATE_SPARSE_BINDING_WRITE,
    MEL_GPU_STATE_EXTERNAL_READ,
    MEL_GPU_STATE_EXTERNAL_WRITE,
} Mel_Gpu_Resource_State;
