#pragma once

#define MEL_TRACK_FLAG_AGGREGATE_SITE (1u << 0)
#define MEL_TRACK_FLAG_AGGREGATE_TAG  (1u << 1)
#define MEL_TRACK_FLAG_BACKTRACE      (1u << 2)

#ifndef MEL_TRACK_BACKTRACE_DEPTH_DEFAULT
#define MEL_TRACK_BACKTRACE_DEPTH_DEFAULT 16u
#endif
