#pragma once

#ifndef MEL_JOB_FIBER_POOL_SIZE
#define MEL_JOB_FIBER_POOL_SIZE 4096
#endif

#ifndef MEL_JOB_FIBER_STACK_SIZE
#define MEL_JOB_FIBER_STACK_SIZE 524288
#endif

#ifndef MEL_JOB_WORK_POOL_SIZE
#define MEL_JOB_WORK_POOL_SIZE 8192
#endif

#ifndef MEL_JOB_PINNED_CAPACITY
#define MEL_JOB_PINNED_CAPACITY 256
#endif

#ifndef MEL_JOB_GLOBAL_CAPACITY
#define MEL_JOB_GLOBAL_CAPACITY 4096
#endif

#ifndef MEL_JOB_SPIN_COUNT
#define MEL_JOB_SPIN_COUNT 20
#endif

#ifndef MEL_JOB_DEBUG_COUNTER_LIFETIME
#ifdef NDEBUG
#define MEL_JOB_DEBUG_COUNTER_LIFETIME 0
#else
#define MEL_JOB_DEBUG_COUNTER_LIFETIME 1
#endif
#endif
