#pragma once

#include <reflect/enum.h>

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum
{
    MEL_SCANCODE_UNKNOWN MEL_SKIP = 0,

    MEL_SCANCODE_A MEL_STR("A") = 4,
    MEL_SCANCODE_B MEL_STR("B"),
    MEL_SCANCODE_C MEL_STR("C"),
    MEL_SCANCODE_D MEL_STR("D"),
    MEL_SCANCODE_E MEL_STR("E"),
    MEL_SCANCODE_F MEL_STR("F"),
    MEL_SCANCODE_G MEL_STR("G"),
    MEL_SCANCODE_H MEL_STR("H"),
    MEL_SCANCODE_I MEL_STR("I"),
    MEL_SCANCODE_J MEL_STR("J"),
    MEL_SCANCODE_K MEL_STR("K"),
    MEL_SCANCODE_L MEL_STR("L"),
    MEL_SCANCODE_M MEL_STR("M"),
    MEL_SCANCODE_N MEL_STR("N"),
    MEL_SCANCODE_O MEL_STR("O"),
    MEL_SCANCODE_P MEL_STR("P"),
    MEL_SCANCODE_Q MEL_STR("Q"),
    MEL_SCANCODE_R MEL_STR("R"),
    MEL_SCANCODE_S MEL_STR("S"),
    MEL_SCANCODE_T MEL_STR("T"),
    MEL_SCANCODE_U MEL_STR("U"),
    MEL_SCANCODE_V MEL_STR("V"),
    MEL_SCANCODE_W MEL_STR("W"),
    MEL_SCANCODE_X MEL_STR("X"),
    MEL_SCANCODE_Y MEL_STR("Y"),
    MEL_SCANCODE_Z MEL_STR("Z"),

    MEL_SCANCODE_1 MEL_STR("1"),
    MEL_SCANCODE_2 MEL_STR("2"),
    MEL_SCANCODE_3 MEL_STR("3"),
    MEL_SCANCODE_4 MEL_STR("4"),
    MEL_SCANCODE_5 MEL_STR("5"),
    MEL_SCANCODE_6 MEL_STR("6"),
    MEL_SCANCODE_7 MEL_STR("7"),
    MEL_SCANCODE_8 MEL_STR("8"),
    MEL_SCANCODE_9 MEL_STR("9"),
    MEL_SCANCODE_0 MEL_STR("0"),

    MEL_SCANCODE_RETURN    MEL_STR("Return"),
    MEL_SCANCODE_ESCAPE    MEL_STR("Escape"),
    MEL_SCANCODE_BACKSPACE MEL_STR("Backspace"),
    MEL_SCANCODE_TAB       MEL_STR("Tab"),
    MEL_SCANCODE_SPACE     MEL_STR("Space"),

    MEL_SCANCODE_MINUS        MEL_STR("Minus"),
    MEL_SCANCODE_EQUALS       MEL_STR("Equals"),
    MEL_SCANCODE_LEFTBRACKET  MEL_STR("LeftBracket"),
    MEL_SCANCODE_RIGHTBRACKET MEL_STR("RightBracket"),
    MEL_SCANCODE_BACKSLASH    MEL_STR("Backslash"),
    MEL_SCANCODE_NONUSHASH    MEL_STR("NonUSHash"),
    MEL_SCANCODE_SEMICOLON    MEL_STR("Semicolon"),
    MEL_SCANCODE_APOSTROPHE   MEL_STR("Apostrophe"),
    MEL_SCANCODE_GRAVE        MEL_STR("Grave"),
    MEL_SCANCODE_COMMA        MEL_STR("Comma"),
    MEL_SCANCODE_PERIOD       MEL_STR("Period"),
    MEL_SCANCODE_SLASH        MEL_STR("Slash"),
    MEL_SCANCODE_CAPSLOCK     MEL_STR("CapsLock"),

    MEL_SCANCODE_F1 MEL_STR("F1"),
    MEL_SCANCODE_F2 MEL_STR("F2"),
    MEL_SCANCODE_F3 MEL_STR("F3"),
    MEL_SCANCODE_F4 MEL_STR("F4"),
    MEL_SCANCODE_F5 MEL_STR("F5"),
    MEL_SCANCODE_F6 MEL_STR("F6"),
    MEL_SCANCODE_F7 MEL_STR("F7"),
    MEL_SCANCODE_F8 MEL_STR("F8"),
    MEL_SCANCODE_F9 MEL_STR("F9"),
    MEL_SCANCODE_F10 MEL_STR("F10"),
    MEL_SCANCODE_F11 MEL_STR("F11"),
    MEL_SCANCODE_F12 MEL_STR("F12"),

    MEL_SCANCODE_PRINTSCREEN MEL_STR("PrintScreen"),
    MEL_SCANCODE_SCROLLLOCK  MEL_STR("ScrollLock"),
    MEL_SCANCODE_PAUSE       MEL_STR("Pause"),
    MEL_SCANCODE_INSERT      MEL_STR("Insert"),
    MEL_SCANCODE_HOME        MEL_STR("Home"),
    MEL_SCANCODE_PAGEUP      MEL_STR("PageUp"),
    MEL_SCANCODE_DELETE      MEL_STR("Delete"),
    MEL_SCANCODE_END         MEL_STR("End"),
    MEL_SCANCODE_PAGEDOWN    MEL_STR("PageDown"),
    MEL_SCANCODE_RIGHT       MEL_STR("Right"),
    MEL_SCANCODE_LEFT        MEL_STR("Left"),
    MEL_SCANCODE_DOWN        MEL_STR("Down"),
    MEL_SCANCODE_UP          MEL_STR("Up"),

    MEL_SCANCODE_LCTRL  MEL_STR("LeftCtrl") = 224,
    MEL_SCANCODE_LSHIFT MEL_STR("LeftShift"),
    MEL_SCANCODE_LALT   MEL_STR("LeftAlt"),
    MEL_SCANCODE_LGUI   MEL_STR("LeftGUI"),
    MEL_SCANCODE_RCTRL  MEL_STR("RightCtrl"),
    MEL_SCANCODE_RSHIFT MEL_STR("RightShift"),
    MEL_SCANCODE_RALT   MEL_STR("RightAlt"),
    MEL_SCANCODE_RGUI   MEL_STR("RightGUI"),

    MEL_SCANCODE_MEDIA_PLAYPAUSE MEL_STR("MediaPlayPause") = 0x10CD,
    MEL_SCANCODE_MEDIA_STOP      MEL_STR("MediaStop")      = 0x10B7,
    MEL_SCANCODE_MEDIA_NEXT      MEL_STR("MediaNext")      = 0x10B5,
    MEL_SCANCODE_MEDIA_PREV      MEL_STR("MediaPrev")      = 0x10B6,
    MEL_SCANCODE_VOLUME_UP       MEL_STR("VolumeUp")       = 0x10E9,
    MEL_SCANCODE_VOLUME_DOWN     MEL_STR("VolumeDown")     = 0x10EA,
    MEL_SCANCODE_MUTE            MEL_STR("Mute")           = 0x10E2,
} Mel_Scancode;
MEL_ENUM_TO_STRING_DEFAULT(Mel_Scancode, "Unknown");

typedef enum
{
    MEL_GAMEPAD_BUTTON_INVALID MEL_SKIP = 0,

    MEL_GAMEPAD_BUTTON_SOUTH MEL_STR("South"),
    MEL_GAMEPAD_BUTTON_EAST  MEL_STR("East"),
    MEL_GAMEPAD_BUTTON_WEST  MEL_STR("West"),
    MEL_GAMEPAD_BUTTON_NORTH MEL_STR("North"),

    MEL_GAMEPAD_BUTTON_BACK  MEL_STR("Back"),
    MEL_GAMEPAD_BUTTON_GUIDE MEL_STR("Guide"),
    MEL_GAMEPAD_BUTTON_START MEL_STR("Start"),

    MEL_GAMEPAD_BUTTON_LEFT_STICK  MEL_STR("LeftStick"),
    MEL_GAMEPAD_BUTTON_RIGHT_STICK MEL_STR("RightStick"),

    MEL_GAMEPAD_BUTTON_LEFT_SHOULDER  MEL_STR("LeftShoulder"),
    MEL_GAMEPAD_BUTTON_RIGHT_SHOULDER MEL_STR("RightShoulder"),

    MEL_GAMEPAD_BUTTON_DPAD_UP    MEL_STR("DpadUp"),
    MEL_GAMEPAD_BUTTON_DPAD_DOWN  MEL_STR("DpadDown"),
    MEL_GAMEPAD_BUTTON_DPAD_LEFT  MEL_STR("DpadLeft"),
    MEL_GAMEPAD_BUTTON_DPAD_RIGHT MEL_STR("DpadRight"),

    MEL_GAMEPAD_BUTTON_MISC1 MEL_STR("Misc1"),

    MEL_GAMEPAD_BUTTON_RIGHT_PADDLE1 MEL_STR("RightPaddle1"),
    MEL_GAMEPAD_BUTTON_LEFT_PADDLE1  MEL_STR("LeftPaddle1"),
    MEL_GAMEPAD_BUTTON_RIGHT_PADDLE2 MEL_STR("RightPaddle2"),
    MEL_GAMEPAD_BUTTON_LEFT_PADDLE2  MEL_STR("LeftPaddle2"),

    MEL_GAMEPAD_BUTTON_TOUCHPAD MEL_STR("Touchpad"),

    MEL_GAMEPAD_BUTTON_COUNT MEL_SKIP,
} Mel_Gamepad_Button;
MEL_ENUM_TO_STRING_DEFAULT(Mel_Gamepad_Button, "Invalid");

typedef enum
{
    MEL_GAMEPAD_AXIS_INVALID MEL_SKIP = 0,

    MEL_GAMEPAD_AXIS_LEFT_X  MEL_STR("LeftX"),
    MEL_GAMEPAD_AXIS_LEFT_Y  MEL_STR("LeftY"),
    MEL_GAMEPAD_AXIS_RIGHT_X MEL_STR("RightX"),
    MEL_GAMEPAD_AXIS_RIGHT_Y MEL_STR("RightY"),

    MEL_GAMEPAD_AXIS_LEFT_TRIGGER  MEL_STR("LeftTrigger"),
    MEL_GAMEPAD_AXIS_RIGHT_TRIGGER MEL_STR("RightTrigger"),

    MEL_GAMEPAD_AXIS_COUNT MEL_SKIP,
} Mel_Gamepad_Axis;
MEL_ENUM_TO_STRING_DEFAULT(Mel_Gamepad_Axis, "Invalid");

#ifdef __cplusplus
}
#endif
