load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

package(default_visibility = ["//visibility:public"])

string_flag(
    name = "gpu",
    build_setting_default = "metal",
    values = ["metal", "vulkan", "webgpu", "d3d12"],
)

[
    config_setting(name = "gpu_" + g, flag_values = {":gpu": g})
    for g in ["metal", "vulkan", "webgpu", "d3d12"]
]

_PLAT_OS = {
    "macos": "@platforms//os:osx",
    "ios": "@platforms//os:ios",
    "linux": "@platforms//os:linux",
    "android": "@platforms//os:android",
    "win32": "@platforms//os:windows",
}

[
    config_setting(name = "plat_" + p, constraint_values = [c])
    for p, c in _PLAT_OS.items()
]

config_setting(
    name = "plat_wasm",
    constraint_values = ["@platforms//cpu:wasm32"],
)

_BACKEND_OS = {
    "cocoa": "@platforms//os:osx",
    "uikit": "@platforms//os:ios",
    "winui": "@platforms//os:windows",
    "androidnative": "@platforms//os:android",
}

[
    config_setting(name = "backend_" + b, constraint_values = [c])
    for b, c in _BACKEND_OS.items()
]

config_setting(
    name = "backend_dom",
    constraint_values = ["@platforms//cpu:wasm32"],
)

_ARCH_CPU = {
    "arm64": "@platforms//cpu:arm64",
    "x86_64": "@platforms//cpu:x86_64",
    "wasm32": "@platforms//cpu:wasm32",
}

[
    config_setting(name = "arch_" + a, constraint_values = [c])
    for a, c in _ARCH_CPU.items()
]
