load("@rules_android//rules:rules.bzl", "android_binary")
load("@rules_apple//apple:macos.bzl", "macos_application")
load("@rules_apple//apple:versioning.bzl", "apple_bundle_version")

package(default_visibility = ["//visibility:public"])

DEPS = ["//modules/boot", "//modules/vat", "//modules/core", "//modules/allocator", "//modules/collection", "//modules/string", "//modules/log", "//modules/time", "//modules/executor", "//modules/future", "//modules/io", "//modules/dialog", "//modules/gui", "//third-party/cppcoro", "//modules/compress", "//modules/compress:compress-rle", "//modules/compress:compress-deflate", "//modules/compress:compress-lz4", "//modules/compress:compress-zstd", "//modules/compress:compress-brotli", "//modules/compress:compress-zip"]

cc_library(
    name = "lib",
    srcs = glob(["src/*.c", "src/*.cc", "src/*.h"]),
    includes = ["src"],
    linkopts = select({"//bazel/config:plat_wasm": ["-sALLOW_MEMORY_GROWTH=1"], "//conditions:default": []}),
    deps = DEPS,
)

cc_binary(
    name = "compress-lab",
    deps = [":lib"],
)

apple_bundle_version(
    name = "version",
    build_version = "1.0.0",
)

macos_application(
    name = "compress-lab_app",
    bundle_id = "orgwall.compresslab",
    bundle_name = "compress-lab",
    infoplists = ["macos/Info.plist"],
    minimum_os_version = "14.4",
    target_compatible_with = ["@platforms//os:macos"],
    version = ":version",
    deps = [":lib"],
)

android_binary(
    name = "melody",
    custom_package = "orgwall.compresslab",
    manifest = "android/AndroidManifest.xml",
    manifest_values = {"appLabel": "Compress Lab"},
    target_compatible_with = ["@platforms//os:android"],
    deps = [
        ":lib",
        "//modules/gui:android_java",
    ],
)
